### ISSUE TITLE
Erro no endpoint de Put

### ISSUE THREAD

**Issue by marcosbrandi** [marcosbrandi/FIAP#2]
Está dando um erro no Put, que não consegui verificar ainda. 
Engraçado é que não mudou a chamada do endpoint em si, tá estranho

**Comment by SolidBigBoss** [comment]
Foi efetuado o teste e o put está funcional
![image](https://github.com/marcosbrandi/FIAP/assets/68247642/e93e77a9-d1cf-4ae3-9acc-905be1e10f7e)
